spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3306/db_user?serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

server:
  port: 8181